version: '3.8'

services:
  my-postgres-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"

  my-go-app:
    image: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_HOST=172.23.0.2
    depends_on:
      - my-postgres-db

  my-react-app:
    image: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - my-go-app
